<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Religion extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		is_login();
		$this->load->model('Setting_app_model');
		$this->load->model('Religion_model');
		$this->load->library('form_validation');
	}

	public function index()
	{
		is_allowed($this->uri->segment(1), null);
		$religion = $this->Religion_model->get_all();
		$data = array(
			'religion_data' => $religion,
			'sett_apps' => $this->Setting_app_model->get_by_id(1),
		);
		$this->template->load('template', 'religion/religion_list', $data);
	}

	public function read($id)
	{
		is_allowed($this->uri->segment(1), 'read');
		$row = $this->Religion_model->get_by_id(decrypt_url($id));
		if ($row) {
			$data = array(
				'religion_id' => $row->religion_id,
				'sett_apps' => $this->Setting_app_model->get_by_id(1),
				'religion_code' => $row->religion_code,
				'religion_name' => $row->religion_name,
			);
			$this->template->load('template', 'religion/religion_read', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('religion'));
		}
	}

	public function create()
	{
		is_allowed($this->uri->segment(1), 'create');
		$data = array(
			'button' => 'Create',
			'action' => site_url('religion/create_action'),
			'sett_apps' => $this->Setting_app_model->get_by_id(1),
			'religion_id' => set_value('religion_id'),
			'religion_code' => set_value('religion_code'),
			'religion_name' => set_value('religion_name'),
		);
		$this->template->load('template', 'religion/religion_form', $data);
	}

	public function create_action()
	{
		is_allowed($this->uri->segment(1), 'create');
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->create();
		} else {
			$data = array(
				'religion_code' => $this->input->post('religion_code', TRUE),
				'religion_name' => $this->input->post('religion_name', TRUE),
			);

			$this->Religion_model->insert($data);
			$this->session->set_flashdata('message', 'Create Record Success');
			redirect(site_url('religion'));
		}
	}

	public function update($id)
	{
		is_allowed($this->uri->segment(1), 'update');
		$row = $this->Religion_model->get_by_id(decrypt_url($id));

		if ($row) {
			$data = array(
				'button' => 'Update',
				'action' => site_url('religion/update_action'),
				'sett_apps' => $this->Setting_app_model->get_by_id(1),
				'religion_id' => set_value('religion_id', $row->religion_id),
				'religion_code' => set_value('religion_code', $row->religion_code),
				'religion_name' => set_value('religion_name', $row->religion_name),
			);
			$this->template->load('template', 'religion/religion_form', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('religion'));
		}
	}

	public function update_action()
	{
		is_allowed($this->uri->segment(1), 'update');
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->update(encrypt_url($this->input->post('religion_id', TRUE)));
		} else {
			$data = array(
				'religion_code' => $this->input->post('religion_code', TRUE),
				'religion_name' => $this->input->post('religion_name', TRUE),
			);

			$this->Religion_model->update($this->input->post('religion_id', TRUE), $data);
			$this->session->set_flashdata('message', 'Update Record Success');
			redirect(site_url('religion'));
		}
	}

	public function delete($id)
	{
		is_allowed($this->uri->segment(1), 'delete');
		$row = $this->Religion_model->get_by_id(decrypt_url($id));

		if ($row) {
			$this->Religion_model->delete(decrypt_url($id));
			$this->session->set_flashdata('message', 'Delete Record Success');
			redirect(site_url('religion'));
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(site_url('religion'));
		}
	}

	public function _rules()
	{
		$this->form_validation->set_rules('religion_code', 'religion code', 'trim|required');
		$this->form_validation->set_rules('religion_name', 'religion name', 'trim|required');

		$this->form_validation->set_rules('religion_id', 'religion_id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Religion.php */
/* Location: ./application/controllers/Religion.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-26 14:40:23 */
/* http://harviacode.com */
