<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trade extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
		$this->load->model('Setting_app_model');
        $this->load->model('Trade_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        $trade = $this->Trade_model->get_all();
        $data = array(
			'sett_apps' => $this->Setting_app_model->get_by_id(1),
            'trade_data' => $trade,
        );
        $this->template->load('template','trade/trade_list', $data);
    }

    public function read($id) 
    {
        is_allowed($this->uri->segment(1),'read');
        $row = $this->Trade_model->get_by_id(decrypt_url($id));
        if ($row) {
            $data = array(
				'sett_apps' => $this->Setting_app_model->get_by_id(1),
				
		'trade_id' => $row->trade_id,
		'trade_code' => $row->trade_code,
		'trade_name' => $row->trade_name,
	    );
            $this->template->load('template','trade/trade_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('trade'));
        }
    }

    public function create() 
    {
        is_allowed($this->uri->segment(1),'create');
        $data = array(
            'button' => 'Create',
			'sett_apps' => $this->Setting_app_model->get_by_id(1),
            'action' => site_url('trade/create_action'),
	    'trade_id' => set_value('trade_id'),
	    'trade_code' => set_value('trade_code'),
	    'trade_name' => set_value('trade_name'),
	);
        $this->template->load('template','trade/trade_form', $data);
    }
    
    public function create_action() 
    {
        is_allowed($this->uri->segment(1),'create');
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'trade_code' => $this->input->post('trade_code',TRUE),
		'trade_name' => $this->input->post('trade_name',TRUE),
	    );

            $this->Trade_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('trade'));
        }
    }
    
    public function update($id) 
    {
        is_allowed($this->uri->segment(1),'update');
        $row = $this->Trade_model->get_by_id(decrypt_url($id));

        if ($row) {
            $data = array(
                'button' => 'Update',
				'sett_apps' => $this->Setting_app_model->get_by_id(1),
                'action' => site_url('trade/update_action'),
		'trade_id' => set_value('trade_id', $row->trade_id),
		'trade_code' => set_value('trade_code', $row->trade_code),
		'trade_name' => set_value('trade_name', $row->trade_name),
	    );
            $this->template->load('template','trade/trade_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('trade'));
        }
    }
    
    public function update_action() 
    {
        is_allowed($this->uri->segment(1),'update');
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
			$this->update(encrypt_url($this->input->post('trade_id', TRUE)));
        } else {
            $data = array(
		'trade_code' => $this->input->post('trade_code',TRUE),
		'trade_name' => $this->input->post('trade_name',TRUE),
	    );

            $this->Trade_model->update($this->input->post('trade_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('trade'));
        }
    }
    
    public function delete($id) 
    {
        is_allowed($this->uri->segment(1),'delete');
        $row = $this->Trade_model->get_by_id(decrypt_url($id));

        if ($row) {
            $this->Trade_model->delete(decrypt_url($id));
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('trade'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('trade'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('trade_code', 'trade code', 'trim|required');
	$this->form_validation->set_rules('trade_name', 'trade name', 'trim|required');

	$this->form_validation->set_rules('trade_id', 'trade_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Trade.php */
/* Location: ./application/controllers/Trade.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-26 14:52:46 */
/* http://harviacode.com */