<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Broker_model extends CI_Model
{

    public $table = 'broker';
    public $id = 'broker_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('broker_id', $q);
	$this->db->or_like('broker_code', $q);
	$this->db->or_like('broker_name', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('name_on_tax', $q);
	$this->db->or_like('address_on_tax', $q);
	$this->db->or_like('npwp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Broker_model.php */
/* Location: ./application/models/Broker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-26 13:33:55 */
/* http://harviacode.com */