<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Insurer_model extends CI_Model
{

    public $table = 'insurer';
    public $id = 'insurer_id';
    public $order = 'DESC';

	public $table2 = 'type_insurer';
    public $id2 = 'type_insurer_id';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

	function get_all_type_insurer()
    {
        $this->db->order_by($this->id2, $this->order);
        return $this->db->get($this->table2)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('insurer_id', $q);
	$this->db->or_like('insurer_code', $q);
	$this->db->or_like('insurer_name', $q);
	$this->db->or_like('address', $q);
	$this->db->or_like('name_on_tax', $q);
	$this->db->or_like('address_on_tax', $q);
	$this->db->or_like('npwp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Insurer_model.php */
/* Location: ./application/models/Insurer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-26 14:50:03 */
/* http://harviacode.com */
