<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Portfolio_model extends CI_Model
{

    public $table = 'portfolio';
    public $id = 'portfolio_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
		$this->db->join('service', 'service.service_id = portfolio.service_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('portfolio_id', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('service_id', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('photo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Portfolio_model.php */
/* Location: ./application/models/Portfolio_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-06 15:57:05 */
/* http://harviacode.com */
